version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: teste
    volumes:
      - ./api/db/data:/home/node/app
    ports:
      - 5432:5432
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    build: ./
    container_name: 'api-server'
    command: sh -c "npm run create_tables && npm start"
    ports:
     - 3001:3001
    volumes:
      - ./:/usr/app
    depends_on:
      - db
    #environment:
     # DB_HOST: db
     # DB_USER: postgres
      #DB_PASS: 123456
      